import "@/app/globals.css";
import { Poppins } from "next/font/google";
import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={`min-h-full ${poppins.variable}`}>
      <body className="flex flex-col min-h-full">
        <Header className="flex-none" />
        <main className="grow">{children}</main>
        <Footer className="flex-none" />
      </body>
    </html>
  );
}
